DROP TABLE IF EXISTS curso_stat;
DROP TABLE IF EXISTS curso;


CREATE TABLE IF NOT EXISTS curso (
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(120) NOT NULL
);

CREATE TABLE IF NOT EXISTS curso_stat (
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    nota DECIMAL (3, 2) NOT NULL DEFAULT 0,
    qtde_alunos INT UNSIGNED NOT NULL DEFAULT 0,
    qtde_acessos INT UNSIGNED NOT NULL DEFAULT 0,
    qtde_avalicoes INT UNSIGNED NOT NULL DEFAULT 0,
    id_curso INT UNSIGNED NOT NULL UNIQUE,
    FOREIGN KEY (id_curso) REFERENCES curso(id)
);