DROP TABLE IF EXISTS ator_filme;
DROP TABLE IF EXISTS filme;
DROP TABLE IF EXISTS ator;


CREATE TABLE IF NOT EXISTS ator (
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(120) NOT NULL
);

CREATE TABLE IF NOT EXISTS filme (
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(120) NOT NULL
);

CREATE TABLE IF NOT EXISTS ator_filme (
    id_ator INT UNSIGNED NOT NULL,
    id_filme INT UNSIGNED NOT NULL,
    nota_atuacao DECIMAL(4, 2) NOT NULL DEFAULT 0,
    PRIMARY KEY(id_ator, id_filme),
    FOREIGN KEY(id_ator) REFERENCES ator(id),
    FOREIGN KEY(id_filme) REFERENCES filme(id)
);